name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # or any version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install torch
          pip install packaging ninja
          pip install -e .
          pip install pytest

      - name: Run Pytest
        run: |
          pytest --ignore csrc/attn/test
