NAME: ace_plus_diffuser_infer
IS_DEFAULT: True
USE_DYNAMIC_MODEL: False
INFERENCE_TYPE: ACE_DIFFUSER_PLUS
DEFAULT_PARAS:
  PARAS:
  #
  INPUT:
    INPUT_IMAGE:
    INPUT_MASK:
    TASK:
    PROMPT: ""
    OUTPUT_HEIGHT: 1024
    OUTPUT_WIDTH: 1024
    SAMPLER: flow_euler
    SAMPLE_STEPS: 28
    GUIDE_SCALE: 50
    SEED: 42
    MAX_SEQ_LENGTH: 4096
  OUTPUT:
    LATENT:
    IMAGES:
    SEED:
MODEL:
  PRETRAINED_MODEL: ${FLUX_FILL_PATH}