name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      python_3_10:
        description: 'Build Python 3.10 image'
        required: false
        default: false
        type: boolean
      python_3_11:
        description: 'Build Python 3.11 image'
        required: false
        default: false
        type: boolean
      python_3_12:
        description: 'Build Python 3.12 image'
        required: false
        default: false
        type: boolean
      python_3_12_cuda_12_9:
        description: 'Build Python 3.12 image Cuda 12.9'
        required: false
        default: false
        type: boolean


permissions:
  contents: read
  packages: write

jobs:
  build-python-3-10:
    if: ${{ github.event.inputs.python_3_10 == 'true' }}
    uses: ./.github/workflows/build-image-template.yml
    with:
      python_version: '3.10'
      dockerfile_path: docker/Dockerfile.python3.10
      tag_suffix: py3.10
    secrets: inherit

  build-python-3-11:
    if: ${{ github.event.inputs.python_3_11 == 'true' }}
    uses: ./.github/workflows/build-image-template.yml
    with:
      python_version: '3.11'
      dockerfile_path: docker/Dockerfile.python3.11
      tag_suffix: py3.11
    secrets: inherit

  build-python-3-12:
    if: ${{ github.event.inputs.python_3_12 == 'true' }}
    uses: ./.github/workflows/build-image-template.yml
    with:
      python_version: '3.12'
      dockerfile_path: docker/Dockerfile.python3.12
      tag_suffix: py3.12
    secrets: inherit

  build-python-3-12-cuda-12-9:
    if: ${{ github.event.inputs.python_3_12_cuda_12_9 == 'true' }}
    uses: ./.github/workflows/build-image-template.yml
    with:
      python_version: '3.12'
      dockerfile_path: docker/Dockerfile.python3.12.cuda12.9.1
      tag_suffix: py3.12-cuda12.9.1
    secrets: inherit