name: Publish to Comfy registry
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

permissions:
  issues: write
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'zombieyang' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.tag_name }}
          name: v${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@v1
        with:
          ## Add your own personal access token to your Github Repository secrets and reference it here.
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
